name: fluttertwitter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  intl: any
  image_picker: ^0.8.5
  firebase_core: ^1.21.1
  firebase_auth: ^3.3.13
  firebase_storage: ^10.3.7  
  cloud_firestore: ^3.1.11
  flutter_svg: ^1.1.0
  adobe_xd: ^2.0.1
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  material_segmented_control: ^3.1.2
  url_launcher: ^6.1.5
  flutter_spinkit: ^5.1.0
  flutter_line_sdk: ^2.2.0
  flutter_riverpod: ^1.0.4
  cloud_functions: ^3.3.6
  provider: ^6.0.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.4.1
  flutter_signin_button: ^2.0.0

dev_dependencies:
 flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: 'images/oliveicon.png'
  remove_alpha_ios: true
  min_sdk_android: 21
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - images/